# Site settings
title: Let's build Utopia!
email: getintouch@youtopi.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.youtopi.org" # the base hostname & protocol for your site

twitter_username: "@youtopiorg"
github_username: youtopi

# Build settings
markdown: kramdown

host:    0.0.0.0
