# Site settings
title: Let's build Utopia!
email: jannis.huebl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.letsbuildutopia.org" # the base hostname & protocol for your site

twitter_username: "@buildUtopia"
github_username: jannishuebl/letsbuildutopia

# Build settings
markdown: kramdown
