# Site settings
title: Our dreaming Cloud
email: jannis.huebl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.our-dreaming.cloud" # the base hostname & protocol for your site

twitter_username: "@OurDreamCloud"
github_username: jannishuebl/our-dreaming-cloud

# Build settings
markdown: kramdown
